### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by madlobakargiideistvis** [Dzoge/sadavicra.ge#14]
Hello! It would be great to have notification system - informing on email, maybe sms, when slots are open.

**Comment by Dzoge** [comment]
საინტერესო შემოთავაზებაა.
ასეთი ფუნქციონალი შედარებით კომპლექსურ ინფრასტრუქტურას მოითხოვს და არ მგონია საწყის ეტაპზე შევძლოთ მაგის გაკეტეთება. backlog-ში ჩავაგდებ რომ მომავალში განვიხილოთ ეს საკითხი.

**Comment by Dzoge** [comment]
> Hello! It would be great to have notification system - informing on email, maybe sms, when slots are open.

საინტერესო შემოთავაზებაა.
ასეთი ფუნქციონალი შედარებით კომპლექსურ ინფრასტრუქტურას მოითხოვს და არ მგონია საწყის ეტაპზე შევძლოთ მაგის გაკეტეთება. backlog-ში ჩავაგდებ რომ მომავალში განვიხილოთ ეს საკითხი.

**Comment by Giorgi** [comment]
Browser-საც შეუძლია ნოტიფიკაციების ჩვენება და არც ინფრასტრუქტურა არ ჭირდება.

**Comment by Dzoge** [comment]
> Browser-საც შეუძლია ნოტიფიკაციების ჩვენება და არც ინფრასტრუქტურა არ ჭირდება.

უმეტესობა iOS-ით შემოდის და ვებ ნოტიფოაკციები მაინც არ იმუშავებს მაგაზე. თუმცა ვიფიქრებ მიდევ ამ საკითხზე.
