### ISSUE TITLE
Problem with registration

### ISSUE THREAD

**Issue by dimson315** [Dzoge/sadavicra.ge#30]
Page shows all available time and place, notwithstanding they are for the first vacination or only for the second

**Comment by Dzoge** [comment]
@dimson315  ამ ეტაპზე არსებული სერვისი არ გვაძლევს იმის ინფორმაციას მოცემული ვაქცინისთვის პრველ დოდაზეა რეგისტრაცია თუ მეორეზე. ვეცდებით რამე გზა გამოვნახოთ.
