### ISSUE TITLE
Linking free slots for better UX

### ISSUE THREAD

**Issue by bakoline** [Dzoge/sadavicra.ge#39]
UX-ისთვის თავისუფალ დროზე რომ დაილინკოს booking.moh.gov.ge-ს ლინკი შესაბამისი ფილტრით ან პირდაპირ კლინკით და რომ გაგრძელდეს რეგისტრაცია

ეს ცოტა მეტ დროს მოითხოვს და ამიტომ, მარტივად და უბრალოდ booking.moh.gov.ge რომ დაილინკოს, ანუ თავისუფალ დროს რომ ეკლიკებოდეს და ზემოთ ასქროლვა არ იყოს საჭირო ან ახალი თაბის გახსნა და ა.შ.

https://imgur.com/a/ejI9gir

პს დიდი მადლობა იმ საქმის კარგად გაკეთებისთვის რაც ვერ გააკეთეს იმათ, ვისაც უნდა გაეკეთებინა ))))

**Comment by Dzoge** [comment]
@bakoline ბუნქინგის ვებ გვერდი არ გვაძლევს იმის საშუალებას რომ რაიმე სახით წინასწარ დაყენდეს ფილტრი ან კონრეტულად რომელიმე სლოტი აირჩიო ეგრევე. თუ მოგცემენ ამის საშუალებას აუცილებლად დავამატებთ.

არსებული მდგომარეობით booking.moh.gov.ge-ზე გადასვლის წინააღმდეგი ვარ, რადგან გაუგებრბას გამოიწვევს ხალხში, issue-ები შემოვა რომ ვაკლიკებ და საიტს მიხსნის სლოტის ნაცვლადო.
